[package]
name = "factorial"
version = "0.1.0"
authors = ["soap"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num = "0.4.0"
itertools = "0.8.2"